version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2

  node1:
    build: .
    environment:
      - NODE_ENV=production

  node2:
    build: .
    environment:
      - NODE_ENV=production
